// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Selected Works documents */
interface SelectedWorksDocumentData {
    /**
     * Work field in *Selected Works*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: selected_works.work[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    work: prismicT.GroupField<Simplify<SelectedWorksDocumentDataWorkItem>>;
    /**
     * Meta Title field in *Selected Works*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: selected_works.meta_title
     * - **Tab**: Meta
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_title: prismicT.KeyTextField;
    /**
     * Meta Description field in *Selected Works*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: selected_works.meta_description
     * - **Tab**: Meta
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_description: prismicT.KeyTextField;
}
/**
 * Item in Selected Works → Work
 *
 */
export interface SelectedWorksDocumentDataWorkItem {
    /**
     * Title field in *Selected Works → Work*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: selected_works.work[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Client field in *Selected Works → Work*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: selected_works.work[].client
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    client: prismicT.KeyTextField;
    /**
     * Video field in *Selected Works → Work*
     *
     * - **Field Type**: Embed
     * - **Placeholder**: *None*
     * - **API ID Path**: selected_works.work[].video
     * - **Documentation**: https://prismic.io/docs/core-concepts/embed
     *
     */
    video: prismicT.EmbedField;
}
/**
 * Selected Works document from Prismic
 *
 * - **API ID**: `selected_works`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SelectedWorksDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<SelectedWorksDocumentData>, "selected_works", Lang>;
export type AllDocumentTypes = SelectedWorksDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { SelectedWorksDocumentData, SelectedWorksDocumentDataWorkItem, SelectedWorksDocument, AllDocumentTypes };
    }
}
